name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21.4"

    - name: Install dependencies
      run: |
        go mod tidy
        go mod download

    # - name: Lint with golangci-lint
    #   uses: golangci/golangci-lint-action@v6
    #   with:
    #     version: v1.58

    - name: Build
      run: go build -v ./cmd/api

    - name: Test
      run: go test -v ./... -coverprofile=coverage.out -coverpkg=./...

    - name: Convert coverage report
      run: go tool cover -func=coverage.out > coverage.txt

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    # - name: Upload coverage report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: coverage-report
    #     path: coverage.txt