name: Release CI/CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21.4"

    - name: Install dependencies
      run: |
        go mod tidy
        go mod download

    - name: Build
      run: go build -v ./cmd/api

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t mariusgrandeandersen/go-api:${{ github.ref_name }} .
        docker push mariusgrandeandersen/go-api:${{ github.ref_name }}